services:
  - type: web
    name: lab
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class gevent --workers 2 --timeout 600 --keep-alive 5
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: wurdle-db
          property: connectionString
    disk:
      name: wurdle-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
