services:
  - type: web
    name: lab
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 2 --timeout 60
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: wurdle-db
          property: connectionString
      - key: PYTHONPATH
        value: /opt/render/project/src
    disk:
      name: wurdle-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
